# Generated by Django 2.2.3 on 2024-02-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='assembly',
            new_name='lga',
        ),
        migrations.RenameField(
            model_name='voters',
            old_name='father_name',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='voters',
            old_name='parliamentary',
            new_name='ward',
        ),
    ]
