# Generated by Django 2.2.3 on 2024-02-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0002_auto_20240205_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='assembly',
            new_name='lga',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='father_name',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='candidates',
            old_name='parliamentary',
            new_name='ward',
        ),
    ]
